version: "3.2"
services:
  php:
    build: 
      context: .
    image: amakundu/cloudswift-php-mysql-demo:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=cloudswift-mysql-app
      - MYSQL_USER=cloudswiftuser
      - MYSQL_PASSWORD=cloudswiftpass
      - MYSQL_DB=cloudswift_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: cloudswift-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=cloudswiftuser
      - MYSQL_PASSWORD=cloudswiftpass 
      - MYSQL_DATABASE=cloudswift_db
    container_name: cloudswift-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=cloudswift-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: cloudswift-phpmyadmin-app
networks:
  frontend:
  backend:
